name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    #needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup
        run: npm install -g semantic-release @semantic-release/github @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/git @semantic-release/release-notes-generator semantic-release-pypi

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install setuptools
        run: python -m pip install --upgrade setuptools wheel twine

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff pre-commit
          pip install -r requirements.txt

      - name: Run linter
        run: git diff --name-only HEAD~10 HEAD | xargs pre-commit run --files

      - name: Run tests
        run: python -m unittest tests/load_tests.py -v
